services:
  app:
    image: iconical/swush-ce:latest
    container_name: swush-app
    restart: unless-stopped
    env_file:
      - ../.env

    ports:
      - "3419:3000"
    volumes:
      - swush-uploads:/data/uploads:rw

volumes:
  swush-uploads:
